---
- name: Converge
  hosts: localhost
  become: true
  gather_facts: true
  serial:
    - 1
    - 2
    - 25%
    - 50%
  vars:
    docker_requirements: docker
    prepare_ubuntu: true
    prepare_centos: true
    prepare_rockylinux: true
    prepare_fedora: true
    prune_ubuntu: false
    prune_centos: false
    prune_rockylinux: false
    prune_fedora: false
    container_default_behavior: 'compatibility'

  roles:
    - role: buluma.docker_env
