---
- name: Converge
  hosts: localhost
  serial:
    - 1
    - 2
    - 25%
    - 50%
  vars:
    prepare_ubuntu: true
    prepare_centos: true
    prepare_rockylinux: true
    prepare_fedora: true
    prune_ubuntu: false
    prune_centos: false
    prune_rockylinux: false
    prune_fedora: false
    container_default_behavior: 'compatibility'
    docker_requirements: docker

  roles:
    - role: ansible-role-docker_env
