---
# This task checks final containers created

- name: Verify
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Verify containers created and running
      ansible.builtin.command: docker ps --filter "status=running"
      changed_when: false
      register: containers

    - ansible.builtin.debug:
        msg: "All containers are running"
      when: containers.stdout_lines | length > 0
